export {  default as Main } from "./main";
export {  default as Profile } from "./profile";
export {  default as Deadline } from "./deadline";
export {  default as CreateTeam } from "./createTeam/CreateTeam";
export {  default as TeamCode } from "./createTeam/teamcode/TeamCode";
export {  default as Teamleader } from "./createTeam/teamleader/Teamleader";
export {  default as Member } from "./createTeam/member/Member";
export {  default as Project } from "./project/Project";
export {  default as Feed } from "./feed/Feed";
